name: Print GitHub Context

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  BASE_DIR: "prod"
  SUB_DIR:  "code"


jobs:
  print-context:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check branch
        run: |
          echo "Current branch is ${{ github.ref }}"
          echo "Current branch is ${{ github.event.pull_request.number }}"
        if: github.event.pull_request && github.event.pull_request.base.ref == 'main'     
      - name: Get Merge Request ID
        id: get_mr_id
        run: |
          # Get the base and head branches from the GitHub event payload
          PULL_REQUEST_NUMBER=$(curl -s \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.groot-preview+json" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${GITHUB_SHA}/pulls" | jq -r '.[0].number')
          echo "PULL_REQUEST_NUMBER=$PULL_REQUEST_NUMBER" >> $GITHUB_ENV
          echo "$PULL_REQUEST_NUMBER"
          echo "Current branch is ${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if:  github.ref == 'refs/heads/main'
          
      - name: Run anything 1
        run: |
          pwd
          echo "My name is Hello"
        if: github.event.pull_request && github.event.pull_request.base.ref == 'main'
      - name: Testing changes
        run: |
          # Fetch the list of changed files in the pull request
          curl -s \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" > merge_request_changes.json
            echo "Saved pull request changes to merge_request_changes.json"
            cat merge_request_changes.json
            CHANGE_COUNT=$(jq -r "[.[] | select(.filename | startswith(\"Infra/${BASE_DIR}/$SUB_DIR/\"))] | length" merge_request_changes.json)
            echo "$CHANGE_COUNT"
        if: github.event.pull_request && github.event.pull_request.base.ref == 'main'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
