name: Print GitHub Context

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  print-context:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check branch
        run: echo "Current branch is ${{ github.ref }}"
      - name: Run anything
        run: |
          pwd
          echo "My name is Hello"
        if: github.event.pull_request && github.event.pull_request.base.ref == 'main'


