name: Print GitHub Context

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  BASE_DIR: "prod"
  SUB_DIR:  "code"


jobs:
  print-context:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check branch
        run: echo "Current branch is ${{ github.ref }}"
        if: github.event_name != 'workflow_dispatch' && github.ref == 'refs/heads/main'
      - name: Run anything 1
        run: |
          pwd
          echo "My name is Hello"
        if: github.event.pull_request && github.event.pull_request.base.ref == 'main'
      - name: Testing changes
        run: |
          # Fetch the list of changed files in the pull request
          curl -s \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" > merge_request_changes.json
            echo "Saved pull request changes to merge_request_changes.json"
            cat merge_request_changes.json
            CHANGE_COUNT=$(jq -r "[.[] | select(.filename | startswith(\"infra/${BASE_DIR}/$SUB_DIR/\"))] | length" merge_request_changes.json)
            echo "$CHANGE_COUNT"
        if: github.event.pull_request && github.event.pull_request.base.ref == 'main'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
