name: Print GitHub Context

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  print-context:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print GitHub context
        run: |
          echo "GitHub Context:"
          echo "${{ toJson(github) }}"
