name: Print GitHub Context

on:
  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  print-context:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git Credentials
        run: |
          export ARM_SKIP_PROVIDER_REGISTRATION=true
          echo "Configuring global git credential helper to enable terraform to pull terraform modules"
          git config --global credential.helper store
          git config --global credential.https://github.com.username gitlab-ci-token
          echo "https://${GH_TOKEN}@github.com" >>~/.git-credentials
          git config --global credential.helper 'store --file ~/.git-credentials'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Specify the version you need

      # Terraform Init
      - name: Terraform Init
        run: terraform init
