name: Print Workflow ID

on:
  workflow_dispatch:

jobs:
  print_id:
    runs-on: ubuntu-latest
    steps:
      - name: Print Workflow ID
        run: echo  ${{ github.run_id }}
    
  print_id2:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Print Workflow ID
        run: echo  ${{ github.run_id }}
    
