name: Print Workflow ID

on:
  workflow_dispatch:
env:
  BASE_DIR: "prod"
  SUB_DIR:  "code"
  RUN_ID: "${{ github.run_id }}"
  RUN_ID1: ${{ github.run_id }}

  
jobs:
  print_id:
    runs-on: ubuntu-latest
    steps:
      - name: Print Workflow ID
        run: echo  ${{ github.run_id }}
    
  print_id2:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Print Workflow ID
        run: echo  ${{ github.run_id }}
  print_id3:
    runs-on: ubuntu-latest
    steps:
      - name: Print Workflow ID
        run: echo  "$BASE_DIR.$SUB_DIR.$RUN_ID.$RUN_ID1
    
