name: Print Workflow ID

on:
  workflow_dispatch:
env:
  BASE_DIR: "prod"
  SUB_DIR:  "code"
  RUN_ID: "${{ github.run_id }}"
  RUN_ID1: ${{ github.run_id }}

  
jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      full_version: ${{ steps.set-output.outputs.full_version }}
    steps:
      - name: Set FULL_VERSION
        id: set-output
        run: echo "full_version=1.0.${{ github.run_id }}" >> "$GITHUB_ENV"

  use-version:
    runs-on: ubuntu-latest
    needs: set-version
    steps:
      - name: Print FULL_VERSION
        run: echo "Using FULL_VERSION:${{ needs.set-version.outputs.full_version }}"


  print_id:
    runs-on: ubuntu-latest
    steps:
      - name: Print Workflow ID
        run: |
          echo  ${{ github.run_id }}
          echo "FULL=$BASE_DIR.$SUB_DIR.$RUN_ID.$RUN_ID" >> $GITHUB_ENV
    
  print_id2:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Print Workflow ID
        run: |
          echo  ${{ github.run_id }}
          echo "FULL=$BASE_DIR.$SUB_DIR.$RUN_ID.$RUN_ID" >> $GITHUB_ENV
  print_id3:
    runs-on: ubuntu-latest
    steps:
      - name: Print Workflow ID
        run: |
          echo  ${{ env.FULL }}
          echo $FULL
    
